//Mark Lindemulder DIG 3480
var GAME_LEVELS = [
  ["x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x            oo                                                                                              x",
   "x                                                                                                            x",
   "x                  xxxxxxx                                                                                   x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                          xxxxxx                                                                            x",
   "x                                                                                                            x",
   "x                                    o                                                                       x",
   "x                                  xxxxxx                                                                    x",
   "x                                                                                                            x",
   "x                                           o                                                                x",
   "x                                         xxxxxx                                                             x",
   "x                            x                                                                               x",
   "x                            x                                                                               x",
   "xo o o o o o o o o o o o o o x                        o                                                      x",
   "x o o=o o o o=o o o o=o o o ox                    xxxxxxxxxxxx                                               x",
   "xiiiiiiiiiiiiiiiiiiiiiiiiiiiixiiiiiiiiiiiiiiiii                                                              x",
   "x                                                                                                            x",
   "x         o                                                           o                                      x",
   "x                                                               xxxxxxxxx                                    x",
   "x                                                                            o                               x",
   "x                                                                            xxxxxiiiiii                     x",
   "x    o                                                                                                       x",
   "x                                                                                                            x",
   "x    @    i          o                                                                        xxxxxxxxxxxxxxxx",
   "x         i         o                                                                         cxxxxxxxxxxxxxxx",
   "x         i        o                                               cxx                        cxxxxxxxxxxxxxxx",
   "x         i       o                                                 cx                        cxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["xxxxxxxxxxxxxxxxxxxxvxxxxxxxvxxxxxxxvxxxxxxxxvxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "x              v       v       v       v              v             v                                         ",
   "x   @                                                                                                         ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                o       o        o       o      o       o      o                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!v!!!!!v!!!!!!!!!v!!!!!v!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
   " !                                  !!!v  !!!v      !!!v  !!!v                                                ",
   " !                                  !!v   !!v       !!v   !!v                                                 ",
   " !                                  !v    !v        !v    !v                                                  ",
   " !                                  v     v         v     v                                                   ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                                                                                                            ",
   " !                o                                                                          !!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["x                                                                                                            x",
   "x                                                                                                            x",
   "x                                               oo                                                           x",
   "x                                                                                                            x",
   "x              oo                              o  o                 o    o                                   x",
   "x              oxxxxxxxxxxxxxxxxxxxx          xxxxxx          xxxxxxxxxxxxxxxxxxx                            x",
   "x              o                                                                                             x",
   "x              o                        ii              ii                                                   x",
   "x              o                                                                                             x",
   "x             xxx                                                                                            x",
   "x                                                                                                            x",
   "x                     oo                                                                                     x",
   "x                                                                                                           ox",
   "x                     xx                                                                 xxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                            x",
   "x                             oo                                                                             x",
   "x                             xx                                                                             x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                    xx               o                   o                   o              x",
   "x                                                                                                            x",
   "x                                           o                   o                   o                        x",
   "x                                          xxx       xxx       xxx       xxx       xxx       xxx             x",
   "x                                                                                               x            x",
   "x                                                                                                x           x",
   "x                                                                                                 x          x",
   "x                                                                                                  x         x",
   "x                                                                                                   x        x",
   "x    @                     o                                                                         x       x",
   "x                                                                                                     x      x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "xxxxxxxxxxx       x       x       x       x       x       x       x       x       x       x       xxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
